# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mehshell < Formula
  desc "Fast, parallelized zsh prompt engine written in Go"
  homepage "https://github.com/blackflame007/mehshell"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blackflame007/mehshell/releases/download/v0.1.8/mehshell_darwin_amd64.tar.gz"
      sha256 "33a7ec68a3c2731e4ef2d9d71620c7d08fdfc2c04a207103d6dc53f060bdd5d5"

      define_method(:install) do
        bin.install "mehshell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blackflame007/mehshell/releases/download/v0.1.8/mehshell_darwin_arm64.tar.gz"
      sha256 "2269062bb74068bbe01558fb7ab393a4c0aeb72dae0671b08ebcad7329d856be"

      define_method(:install) do
        bin.install "mehshell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackflame007/mehshell/releases/download/v0.1.8/mehshell_linux_amd64.tar.gz"
      sha256 "aa35dbc9eb53fe2712f5e8f29307a22974754cb4f80a82bae85200b325adc194"
      define_method(:install) do
        bin.install "mehshell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blackflame007/mehshell/releases/download/v0.1.8/mehshell_linux_arm64.tar.gz"
      sha256 "6788035d95de8888ba6e6b9e513d34ec45f3a82e809231b3d512e1f49c575cc7"
      define_method(:install) do
        bin.install "mehshell"
      end
    end
  end
end
